routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () { return view('welcome');});
Route::get('/', 'FrontendController@index');
Route::get('masjid_v1/getWaktuAzan','FrontendController@getWaktuAzan');
Route::get('prokes', 'ProkesController@index');
Route::get('prokesSholatJumat', 'ProkesController@prokesJumat');
Route::get('masjid_v1/getWaktuIqomah','ProkesController@getWaktuIqomah');
Route::get('countdownblank', 'ProkesController@blankscreen');
Route::get('countdownblankSholatJumat', 'ProkesController@blankscreenJumat');

// * ROUTE BACK END
Route::get('/masjidadminlogin', function () {return view('backEND.loginmasjid');});

Route::group(['middleware' => 'auth'],function(){
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('users', 'UserController');
    Route::resource('infoprogrammasjid', 'InfoProgramMasjidController');
    Route::resource('infosholatjumat', 'InfoSholatJumatController');
    Route::resource('infokajianmingguan', 'InfoKajianMingguanController');
    Route::resource('infokepengurusan', 'InfoKepengurusanController');
    Route::resource('hadits', 'HaditsController');
    Route::resource('jedawaktu', 'JedaWaktuController');
   

    // * view create
    Route::get('actionviewbeforeazan', 'JedaWaktuController@createViewBeforeAzan');
    Route::get('actionviewiqomah', 'JedaWaktuController@createViewIqomah');

    // * action add
    Route::post("actioncreatebeforeazan", "JedaWaktuController@createActionBeforeAzan");
    Route::post("actioncreateiqomah", "JedaWaktuController@createActionIqomah");

    // * view edit
    Route::get('editviewbeforeazan/{id}', 'JedaWaktuController@vieweditBeforeAzan');
    Route::get('editviewiqomah/{id}', 'JedaWaktuController@vieweditIqomah');

    // * action update
    Route::get("actionupdatebeforeazan/{id}", "JedaWaktuController@updateActionBeforeAzan");
    Route::get("actionupdateiqomah/{id}", "JedaWaktuController@updateActionIqomah");

    // * action delete
    // Route::get("actiondeletebeforeazan/{id}", "JedaWaktuController@destroyBeforeAzan");
    // Route::get("actiondeleteiqomah/{id}", "JedaWaktuController@destroyIqomah");
  
    Route::get('UpdatePhotoEmpty/{id}', 'InfoSholatJumatController@UpdatePhotoEmpty')->name('UpdatePhotoEmpty.UpdatePhotoEmpty');
    Route::get('UpdatePhotoEmptyKajian/{id}', 'InfoKajianMingguanController@UpdatePhotoEmptyKajian')->name('UpdatePhotoEmptyKajian.UpdatePhotoEmptyKajian');
});

Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/HaditsController.php
<?php

namespace App\Http\Controllers;

use Hash;
use Auth;
use Storage;
use View;

use App\User;
use App\MHadits;

use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Crypt;
use Illuminate\Support\Facades\DB;

class HaditsController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }


    public function index()
    {
        $data['m_hadits'] = MHadits::all();

        return view('backEND.Hadits.view', $data);
    }

    
    public function create()
    {
        return view('backEND.Hadits.create');
    }


    public function store(Request $request)
    {
        date_default_timezone_set('Asia/Jakarta');
        $userID      = Auth::id();
        $today       = date("Y-m-d H:i:s"); 

        $all_data_hadits = [
            'konten'        => $request->konten,
            'insert_by'     => $userID,
            'created_at'    => $today,
        ];
    
        $save = MHadits::insert($all_data_hadits);
        if($save)
            return redirect('hadits');
        else
            return redirect()->back()->withInput();
    }

    
    public function show($id)
    {
        //
    }

    
    public function edit($id)
    {
        $data['m_hadits'] = MHadits::find($id);
     
        return view('backEND.Hadits.edit')->with(['data' => $data]);
    }

    
    public function update(Request $request, $id)
    {
        date_default_timezone_set('Asia/Jakarta');
        $userID      = Auth::id();
        $today       = date("Y-m-d H:i:s"); 

        $updateHadits = [
            'konten'        => $request->konten,
            'update_by'     => $userID,
            'updated_at'    => $today,
        ];

        $updatedata = MHadits::where('id',$id)->update($updateHadits);
        if($updatedata){
            $msg = 'Your data has been successfully updated!';
        return redirect('hadits')->withSuccess($msg);
        } else {
            return redirect()->back()->withInput();
        }
    }

    
    public function destroy($id)
    {
        $deletehadits = MHadits::find($id);
        if($deletehadits) {
            $deletehadits->destroy($id);
            $msg = 'Your data has been deleted!';
        } else {
            $msg = 'Please try again!';
        }
        return redirect()
            ->back()
            ->withSuccess($msg); 
    }
}

resources/views/backEND/Hadits/create.blade.php
@extends('backEND.layouts.index')

@section('page-content')

<div class="pcoded-content">
        <div class="pcoded-inner-content">
           <div class="main-body">
              <div class="page-wrapper">
                 {{-- BREADCRUMD --}}
                 <div class="page-header">
                    <div class="page-header-title">
                       <h4>Create Hadits - Hadits</h4>
                    </div>
                    <div class="page-header-breadcrumb">
                       <ul class="breadcrumb-title">
                          <li class="breadcrumb-item">
                             <a href="index-2.html">
                             <i class="icofont icofont-home"></i>
                             </a>
                          </li>
                          <li class="breadcrumb-item"><a href="#!">Hadits - Hadits</a></li>
                          <li class="breadcrumb-item"><a href="#!">Create Hadits - Hadits</a></li>
                       </ul>
                    </div>
                 </div>
                 {{-- END BREADCRUMD --}}
                 <div class="page-body">
                    <div class="row">
                       <div class="col-lg-12">
                          <div class="card">
                             <div class="card-header">
                                <h5>Create Hadits - Hadits</h5>
                             </div>
                             <div class="card-block">
                                <form id="main" method="post" action="{{ URL('hadits/') }}{{ isset($MHadits) ? '/' . $MHadits->id : '' }}" enctype="multipart/form-data" id="myReset">
                                {{ csrf_field() }}
                            	@if (isset($MHadits))
									{{ method_field('PUT') }}
								@endif    
                                    <div class="form-group row">
                                        <label class="col-sm-2 col-form-label">Konten Hadits</label>
                                        <div class="col-sm-10">
                                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                            <input type="file" id="image-input" style="display: none;">
                                            <textarea rows="5" cols="5" class="form-control form-control-danger" name="konten"></textarea>
                                        </div>
                                    </div>
                                   
                                    <div class="form-group row">
                                        <label class="col-sm-2"></label>
                                        <div class="col-sm-10">
                                            <button type="submit" class="btn btn-danger m-b-0">Reset</button>
                                            <button type="submit" class="btn btn-primary m-b-0">Submit</button>
                                        </div>
                                    </div>
                                </form>
            
                             </div>
                          </div>
                       </div>
                    </div>
                 </div>
              </div>
              <!-- UNTUK SETTING COLOR -->
              <div id="styleSelector"></div>
           </div>
        </div>
     </div>

@endsection

@section('js')
<script src="{{ asset('public/vendor/unisharp/laravel-ckeditor/ckeditor.js') }}"></script>
<script src="{{ asset('public/vendor/unisharp/laravel-ckeditor/adapters/jquery.js') }}"></script>
<script>
    $('textarea').ckeditor();
    // $('.textarea').ckeditor(); // if class is prefered.
</script>
@endsection

resources/views/backEND/Hadits/edit.blade.php
@extends('backEND.layouts.index')

@section('page-content')

<div class="pcoded-content">
        <div class="pcoded-inner-content">
           <div class="main-body">
              <div class="page-wrapper">
                 {{-- BREADCRUMD --}}
                 <div class="page-header">
                    <div class="page-header-title">
                       <h4>Edit Hadits - Hadits</h4>
                    </div>
                    <div class="page-header-breadcrumb">
                       <ul class="breadcrumb-title">
                          <li class="breadcrumb-item">
                             <a href="index-2.html">
                             <i class="icofont icofont-home"></i>
                             </a>
                          </li>
                          <li class="breadcrumb-item"><a href="#!">Hadits - Hadits</a></li>
                          <li class="breadcrumb-item"><a href="#!">Edit Hadits - Hadits</a></li>
                       </ul>
                    </div>
                 </div>
                 {{-- END BREADCRUMD --}}
                 <div class="page-body">
                    <div class="row">
                       <div class="col-lg-12">
                          <div class="card">
                             <div class="card-header">
                                <h5>Edit Hadits - Hadits</h5>
                             </div>
                             <div class="card-block">
                                <form id="main" method="post" action="{{ URL::to('hadits',$data['m_hadits']->id)}}" enctype="multipart/form-data" id="myReset">
                                {{ csrf_field() }}
                                {{ method_field('put') }}
                                    <div class="form-group row">
                                        <label class="col-sm-2 col-form-label">Konten Hadits</label>
                                        <div class="col-sm-10">
                                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                            <input type="file" id="image-input" style="display: none;">
                                            <textarea rows="5" cols="5" class="form-control form-control-danger" name="konten">{{ isset($data['m_hadits']) ? $data['m_hadits']->konten : '' }}</textarea>
                                        </div>
                                    </div>
                                   
                                    <div class="form-group row">
                                        <label class="col-sm-2"></label>
                                        <div class="col-sm-10">
                                            <button type="submit" class="btn btn-danger m-b-0">Reset</button>
                                            <button type="submit" class="btn btn-primary m-b-0">Update</button>
                                        </div>
                                    </div>
                                </form>
            
                             </div>
                          </div>
                       </div>
                    </div>
                 </div>
              </div>
              <!-- UNTUK SETTING COLOR -->
              <div id="styleSelector"></div>
           </div>
        </div>
     </div>

@endsection

@section('js')
<script src="{{ asset('public/vendor/unisharp/laravel-ckeditor/ckeditor.js') }}"></script>
<script src="{{ asset('public/vendor/unisharp/laravel-ckeditor/adapters/jquery.js') }}"></script>
<script>
    $('textarea').ckeditor();
    // $('.textarea').ckeditor(); // if class is prefered.
</script>
@endsection

resources/views/backEND/Hadits/view.blade.php
@extends('backEND.layouts.index')

@section('page-content')
<div class="pcoded-content">
    <div class="pcoded-inner-content">
        <div class="main-body">
            <div class="page-wrapper">
                {{-- BREADCRUMD --}}
                <div class="page-header">
                    <div class="page-header-title">
                        <h4>Hadits - Hadits</h4>
                    </div>
                    <div class="page-header-breadcrumb">
                        <ul class="breadcrumb-title">
                            <li class="breadcrumb-item">
                                <a href="index-2.html">
                                <i class="icofont icofont-home"></i>
                                </a>
                            </li>
                            {{-- <li class="breadcrumb-item"><a href="#!"></a></li> --}}
                            <li class="breadcrumb-item"><a href="#!">Hadits - Hadits</a></li>
                        </ul>
                    </div>
                </div>
                {{-- END BREADCRUMD --}}
                <div class="page-body">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="card">
                                <div class="card-header">
                                    <h5>Hadits - Hadits</h5>
                                    <div class="card-header-right">
                                        <a class="btn btn-primary" href="{{ URL('hadits/create') }}">
                                            <i class="icofont icofont-ui-add"></i>
                                            Add Hadits - hadits
                                        </a>
                                    </div>
                                </div>
                                <div class="card-block">

                                    <table id="example" class="display" style="width:100%">
                                        <thead>
                                            <tr>
                                                <th>No</th>
                                                <th>Konten</th>
                                                <th>Action</th>
                                            </tr>
                                        </thead>
                                        
                                        <tbody>
                                            @foreach ($m_hadits as $key => $data)
                                            <tr>
                                                <td>{{ ($key+1) }}</td>
                                                <td>{{ $data->konten }}</td>
                                                
                                                <td>
                                                    <a href="{{ route('hadits.edit', $data->id) }}" type="button" title="Edit" class="btn btn-warning btn-sm">
                                                        <i class="icofont icofont-pencil"></i>
                                                    </a>
                                                    
                                                    <form id="delete" action="{{ route('hadits.destroy', $data->id) }}" 
                                                        method="POST" style="display: inline;">
                                                        {{ csrf_field() }}
                                                        {{ method_field('DELETE') }}
                                                        <button title="Delete" class="btn btn-danger btn-sm"><i class="icofont icofont-trash"></i></button>
                                                    </form>
                                                </td>
                                            </tr>
                                            @endforeach
                                        </tbody>
                                    </table>
                                    
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- UNTUK SETTING COLOR -->
            <div id="styleSelector">
            </div>
        </div>
    </div>
</div>
                
@endsection

@section('js')
<script src="{{ asset('public/asset_admin/assets/js/datatables/js/datatables.min.js') }}"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $('#example').DataTable();
    } );
</script>

@endsection