routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () { return view('welcome');});
Route::get('/', 'FrontendController@index');
Route::get('masjid_v1/getWaktuAzan','FrontendController@getWaktuAzan');
Route::get('prokes', 'ProkesController@index');
Route::get('prokesSholatJumat', 'ProkesController@prokesJumat');
Route::get('masjid_v1/getWaktuIqomah','ProkesController@getWaktuIqomah');
Route::get('countdownblank', 'ProkesController@blankscreen');
Route::get('countdownblankSholatJumat', 'ProkesController@blankscreenJumat');

// * ROUTE BACK END
Route::get('/masjidadminlogin', function () {return view('backEND.loginmasjid');});

Route::group(['middleware' => 'auth'],function(){
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('users', 'UserController');
    Route::resource('infoprogrammasjid', 'InfoProgramMasjidController');
    Route::resource('infosholatjumat', 'InfoSholatJumatController');
    Route::resource('infokajianmingguan', 'InfoKajianMingguanController');
    Route::resource('infokepengurusan', 'InfoKepengurusanController');
    Route::resource('hadits', 'HaditsController');
    Route::resource('jedawaktu', 'JedaWaktuController');
   

    // * view create
    Route::get('actionviewbeforeazan', 'JedaWaktuController@createViewBeforeAzan');
    Route::get('actionviewiqomah', 'JedaWaktuController@createViewIqomah');

    // * action add
    Route::post("actioncreatebeforeazan", "JedaWaktuController@createActionBeforeAzan");
    Route::post("actioncreateiqomah", "JedaWaktuController@createActionIqomah");

    // * view edit
    Route::get('editviewbeforeazan/{id}', 'JedaWaktuController@vieweditBeforeAzan');
    Route::get('editviewiqomah/{id}', 'JedaWaktuController@vieweditIqomah');

    // * action update
    Route::get("actionupdatebeforeazan/{id}", "JedaWaktuController@updateActionBeforeAzan");
    Route::get("actionupdateiqomah/{id}", "JedaWaktuController@updateActionIqomah");

    // * action delete
    // Route::get("actiondeletebeforeazan/{id}", "JedaWaktuController@destroyBeforeAzan");
    // Route::get("actiondeleteiqomah/{id}", "JedaWaktuController@destroyIqomah");
  
    Route::get('UpdatePhotoEmpty/{id}', 'InfoSholatJumatController@UpdatePhotoEmpty')->name('UpdatePhotoEmpty.UpdatePhotoEmpty');
    Route::get('UpdatePhotoEmptyKajian/{id}', 'InfoKajianMingguanController@UpdatePhotoEmptyKajian')->name('UpdatePhotoEmptyKajian.UpdatePhotoEmptyKajian');
});

Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/InfoProgramMasjidController.php
<?php

namespace App\Http\Controllers;

use Hash;
use Auth;
use Storage;
use View;

use App\User;
use App\MInfoProgramMasjids;

use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Crypt;
use Illuminate\Support\Facades\DB;

class InfoProgramMasjidController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $data['m_info_program_masjids'] = MInfoProgramMasjids::all();

        return view('backEND.InfoProgramMasjid.view', $data);
    }

    public function create()
    {
        return view('backEND.InfoProgramMasjid.create');
    }

    public function store(Request $request)
    {
        date_default_timezone_set('Asia/Jakarta');
        $userID      = Auth::id();
        $today       = date("Y-m-d H:i:s"); 
        $tanggal = "";
        
        if($request->pilih_waktu == "tanggal"){
            $all_data_program = [
                'pilih_waktu'    => $request->pilih_waktu,
                'tanggal'       => date('Y-m-d', strtotime($request->tanggal)),
                'judul'         => $request->judul,
                'konten'        => $request->konten,
                'insert_by'     => $userID,
                'created_at'    =>  $today,
            ];
        } else {
            $all_data_program = [
                'pilih_waktu'    => $request->pilih_waktu,
                'waktu_teks'    => $request->waktu_teks,
                'judul'         => $request->judul,
                'konten'        => $request->konten,
                'insert_by'     => $userID,
                'created_at'    =>  $today,
            ];
        }

        
        // dd($all_data_blogger);die;
    
        $save = MInfoProgramMasjids::insert($all_data_program);
        if($save)
            return redirect('infoprogrammasjid');
        else
            return redirect()->back()->withInput();
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $data['m_info_program_masjids'] = MInfoProgramMasjids::find($id);
     
        return view('backEND.InfoProgramMasjid.edit')->with(['data' => $data]);
    }

    public function update(Request $request, $id)
    {
        date_default_timezone_set('Asia/Jakarta');
        $userID      = Auth::id();
        $today       = date("Y-m-d H:i:s"); 

        if($request->pilih_waktu == "tanggal"){
            $updateKegiatan = [
                'pilih_waktu'   => $request->pilih_waktu,
                'tanggal'       => date('Y-m-d', strtotime($request->tanggal)),
                'waktu_teks'    => '',
                'judul'         => $request->judul,
                'konten'        => $request->konten,
                'update_by'     => $userID,
                'updated_at'    => $today,
            ];
        } else {
            $updateKegiatan = [
                'pilih_waktu'   => $request->pilih_waktu,
                'tanggal'       => '',
                'waktu_teks'    => $request->waktu_teks,
                'judul'         => $request->judul,
                'konten'        => $request->konten,
                'update_by'     => $userID,
                'updated_at'    => $today,
            ];
        }

       // dd($updateKegiatan);die;
        $updatedata = MInfoProgramMasjids::where('id',$id)->update($updateKegiatan);
        if($updatedata){
            $msg = 'Your data has been successfully updated!';
        return redirect('infoprogrammasjid')->withSuccess($msg);
        } else {
            return redirect()->back()->withInput();
        }
    }

    public function destroy($id)
    {
        $programMasjid = MInfoProgramMasjids::find($id);
        if($programMasjid) {
            $programMasjid->destroy($id);
            $msg = 'Your data has been deleted!';
        } else {
            $msg = 'Please try again!';
        }
        return redirect()
            ->back()
            ->withSuccess($msg); 
    }
}

resources/views/backEND/InfoProgramMasjid/create.blade.php
@extends('backEND.layouts.index')

@section('page-content')

<div class="pcoded-content">
        <div class="pcoded-inner-content">
           <div class="main-body">
              <div class="page-wrapper">
                 {{-- BREADCRUMD --}}
                 <div class="page-header">
                    <div class="page-header-title">
                       <h4>Create Program Masjid</h4>
                    </div>
                    <div class="page-header-breadcrumb">
                       <ul class="breadcrumb-title">
                          <li class="breadcrumb-item">
                             <a href="index-2.html">
                             <i class="icofont icofont-home"></i>
                             </a>
                          </li>
                          <li class="breadcrumb-item"><a href="#!">Program Masjid</a></li>
                          <li class="breadcrumb-item"><a href="#!">Create Program Masjid</a></li>
                       </ul>
                    </div>
                 </div>
                 {{-- END BREADCRUMD --}}
                 <div class="page-body">
                    <div class="row">
                       <div class="col-lg-12">
                          <div class="card">
                             <div class="card-header">
                                <h5>Create Program Masjid</h5>
                             </div>
                             <div class="card-block">
                                 <form id="main" method="post" action="{{ URL('infoprogrammasjid/') }}{{ isset($MInfoProgramMasjids) ? '/' . $MInfoProgramMasjids->id : '' }}" enctype="multipart/form-data" id="myReset">
                                 {{ csrf_field() }}
                                 @if (isset($MInfoProgramMasjids))
                                    {{ method_field('PUT') }}
                                 @endif    
                                    <div class="form-group row">
                                        <label class="col-sm-2 col-form-label">Pilih Waktu</label>
                                        <div class="col-sm-5">
                                             <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                             <select name="pilih_waktu" class="form-control" id="pilih_waktu">
                                                   <option value="">--- Pilih Waktu ---</option>
                                                   <option value="tanggal">Waktu Tanggal</option>
                                                   <option value="teks">Waktu Teks</option>
                                             </select>
                                        </div>
                                    </div>
                                    <div id="waktu_tanggal" class="form-group row" style="display:none">
                                        <label class="col-sm-2 col-form-label">Waktu Tanggal</label>
                                        <div class="col-sm-5">
                                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                            <input 
                                            id="dropper-default" 
                                            class="form-control form-control-danger" 
                                            type="text" 
                                            name="tanggal" 
                                            >
                                        </div>
                                    </div>
                                    <div id="waktu_teks" class="form-group row" style="display:none">
                                        <label class="col-sm-2 col-form-label">Waktu Teks</label>
                                        <div class="col-sm-5">
                                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                            <input 
                                            class="form-control form-control-danger" 
                                            type="text" 
                                            name="waktu_teks" 
                                            >
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-sm-2 col-form-label">Judul Kegiatan</label>
                                        <div class="col-sm-10">
                                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                            <input type="text" name="judul" class="form-control form-control-danger">
                                            <span class="messages"></span>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-sm-2 col-form-label">Acara Kegiatan</label>
                                        <div class="col-sm-10">
                                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                            <input type="file" id="image-input" style="display: none;">
                                            <textarea rows="5" cols="5" class="form-control form-control-danger" name="konten"></textarea>
                                        </div>
                                    </div>
                                   
                                    <div class="form-group row">
                                        <label class="col-sm-2"></label>
                                        <div class="col-sm-10">
                                            <button type="submit" class="btn btn-danger m-b-0">Reset</button>
                                            <button type="submit" class="btn btn-primary m-b-0">Submit</button>
                                        </div>
                                    </div>
                                </form>
            
                             </div>
                          </div>
                       </div>
                    </div>
                 </div>
              </div>
              <!-- UNTUK SETTING COLOR -->
              <div id="styleSelector"></div>
           </div>
        </div>
     </div>

@endsection

@section('js')
<script src="{{ asset('public/vendor/unisharp/laravel-ckeditor/ckeditor.js') }}"></script>
<script src="{{ asset('public/vendor/unisharp/laravel-ckeditor/adapters/jquery.js') }}"></script>
<script type="text/javascript" src="{{ asset('public/asset_admin/bower_components/datedropper/datedropper.min.js') }}"></script>
<script>
$("#pilih_waktu").change(function() {
   if ($(this).val() == "tanggal") {
         $("#waktu_tanggal").show();
   } else  {
         $("#waktu_tanggal").hide();
   }

   if ($(this).val() == "teks") {
         $("#waktu_teks").show();
   } else  {
         $("#waktu_teks").hide();
   }
});
</script>

<script>
   $('#dropper-default').dateDropper({
      theme: 'leaf'
   });
</script> 
<script>
    $('textarea').ckeditor();
    // $('.textarea').ckeditor(); // if class is prefered.
</script>
@endsection

resources/views/backEND/InfoProgramMasjid/edit.blade.php
@extends('backEND.layouts.index')

@section('page-content')

<div class="pcoded-content">
        <div class="pcoded-inner-content">
           <div class="main-body">
              <div class="page-wrapper">
                 {{-- BREADCRUMD --}}
                 <div class="page-header">
                    <div class="page-header-title">
                       <h4>Edit Program Masjid</h4>
                    </div>
                    <div class="page-header-breadcrumb">
                       <ul class="breadcrumb-title">
                          <li class="breadcrumb-item">
                             <a href="index-2.html">
                             <i class="icofont icofont-home"></i>
                             </a>
                          </li>
                          <li class="breadcrumb-item"><a href="#!">Info Program Masjid</a></li>
                          <li class="breadcrumb-item"><a href="#!">Edit Program Masjid</a></li>
                       </ul>
                    </div>
                 </div>
                 {{-- END BREADCRUMD --}}
                 <div class="page-body">
                    <div class="row">
                       <div class="col-lg-12">
                          <div class="card">
                             <div class="card-header">
                                <h5>Edit Program Masjid</h5>
                             </div>
                             <div class="card-block">
                                <form id="main" method="post" action="{{ URL::to('infoprogrammasjid',$data['m_info_program_masjids']->id)}}" enctype="multipart/form-data" id="myReset">
                                {{ csrf_field() }}
                                {{ method_field('put') }}
                                    <div class="form-group row">
                                        <label class="col-sm-2 col-form-label">Pilih Waktu</label>
                                        <div class="col-sm-5">
                                             <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                             <select name="pilih_waktu" class="form-control" id="pilih_waktu">
                                                   <option value="" @if($data['m_info_program_masjids']->pilih_waktu == '') selected @endif>--- Pilih Waktu ---</option>
                                                   <option value="tanggal" {{ $data['m_info_program_masjids']->pilih_waktu == 'tanggal' ? 'selected' : ''}}>Waktu Tanggal</option>
                                                   <option value="teks" {{ $data['m_info_program_masjids']->pilih_waktu == 'teks' ? 'selected' : ''}}>Waktu Teks</option>
                                             </select>
                                        </div>
                                    </div>
               
                                    @if($data['m_info_program_masjids']->pilih_waktu == 'tanggal')
                                    <div id="waktu_tanggal"  class="form-group row">
                                        <label class="col-sm-2 col-form-label">Tanggal Kegiatan</label>
                                        <div class="col-sm-5">
                                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                            <input 
                                            id="dropper-default" 
                                            class="form-control form-control-danger" 
                                            type="text" 
                                            name="tanggal" 
                                            value="{{ isset($data['m_info_program_masjids']) ? $data['m_info_program_masjids']->tanggal : '' }}"
                                            >
                                        </div>
                                    </div>
                                    @else
                                    <div id="waktu_tanggal"  class="form-group row" style="display:none">
                                        <label class="col-sm-2 col-form-label">Tanggal Kegiatan</label>
                                        <div class="col-sm-5">
                                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                            <input 
                                            id="dropper-default" 
                                            class="form-control form-control-danger" 
                                            type="text" 
                                            name="tanggal" 
                                            value="{{ isset($data['m_info_program_masjids']) ? $data['m_info_program_masjids']->tanggal : '' }}"
                                            >
                                        </div>
                                    </div>
                                    @endif

                                    @if($data['m_info_program_masjids']->pilih_waktu == 'teks')
                                    <div id="waktu_teks" class="form-group row">
                                        <label class="col-sm-2 col-form-label">Waktu Teks</label>
                                        <div class="col-sm-5">
                                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                            <input 
                                            class="form-control form-control-danger" 
                                            type="text" 
                                            name="waktu_teks" 
                                            value="{{ isset($data['m_info_program_masjids']) ? $data['m_info_program_masjids']->waktu_teks : '' }}"
                                            >
                                        </div>
                                    </div>
                                    @else
                                    <div id="waktu_teks" class="form-group row" style="display:none">
                                        <label class="col-sm-2 col-form-label">Waktu Teks</label>
                                        <div class="col-sm-5">
                                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                            <input 
                                            class="form-control form-control-danger" 
                                            type="text" 
                                            name="waktu_teks" 
                                            value="{{ isset($data['m_info_program_masjids']) ? $data['m_info_program_masjids']->waktu_teks : '' }}"
                                            >
                                        </div>
                                    </div>
                                    @endif

                                    <div class="form-group row">
                                        <label class="col-sm-2 col-form-label">Judul Kegiatan</label>
                                        <div class="col-sm-10">
                                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                            <input type="text" name="judul" value="{{ isset($data['m_info_program_masjids']) ? $data['m_info_program_masjids']->judul : '' }}"  class="form-control form-control-danger">
                                            <span class="messages"></span>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-sm-2 col-form-label">Acara Kegiatan</label>
                                        <div class="col-sm-10">
                                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                            <input type="file" id="image-input" style="display: none;">
                                            <textarea rows="5" cols="5" class="form-control form-control-danger" name="konten">{{ isset($data['m_info_program_masjids']) ? $data['m_info_program_masjids']->konten : '' }}</textarea>
                                        </div>
                                    </div>
                                   
                                    <div class="form-group row">
                                        <label class="col-sm-2"></label>
                                        <div class="col-sm-10">
                                            <button type="submit" class="btn btn-danger m-b-0">Reset</button>
                                            <button type="submit" class="btn btn-primary m-b-0">Submit</button>
                                        </div>
                                    </div>
                                </form>
            
                             </div>
                          </div>
                       </div>
                    </div>
                 </div>
              </div>
              <!-- UNTUK SETTING COLOR -->
              <div id="styleSelector"></div>
           </div>
        </div>
     </div>

@endsection

@section('js')
<script src="{{ asset('public/vendor/unisharp/laravel-ckeditor/ckeditor.js') }}"></script>
<script src="{{ asset('public/vendor/unisharp/laravel-ckeditor/adapters/jquery.js') }}"></script>
<script type="text/javascript" src="{{ asset('public/asset_admin/bower_components/datedropper/datedropper.min.js') }}"></script>
<script>
   $("#pilih_waktu").change(function() {
      // alert('masuk');
      if ($('#pilih_waktu').val() == "tanggal") {
            $("#waktu_tanggal").show();
      } else  {
            $("#waktu_tanggal").hide();
      }

      if ($('#pilih_waktu').val() == "teks") {
            $("#waktu_teks").show();
      } else  {
            $("#waktu_teks").hide();
      }
   });
</script>
<script>
   $('#dropper-default').dateDropper({
      theme: 'leaf'
   });
</script> 
<script>
    $('textarea').ckeditor();
    // $('.textarea').ckeditor(); // if class is prefered.
</script>
@endsection

resources/views/backEND/InfoProgramMasjid/view.blade.php
@extends('backEND.layouts.index')

@section('page-content')
<div class="pcoded-content">
    <div class="pcoded-inner-content">
        <div class="main-body">
            <div class="page-wrapper">
                {{-- BREADCRUMD --}}
                <div class="page-header">
                    <div class="page-header-title">
                        <h4>Info Program Masjid</h4>
                    </div>
                    <div class="page-header-breadcrumb">
                        <ul class="breadcrumb-title">
                            <li class="breadcrumb-item">
                                <a href="index-2.html">
                                <i class="icofont icofont-home"></i>
                                </a>
                            </li>
                            {{-- <li class="breadcrumb-item"><a href="#!"></a></li> --}}
                            <li class="breadcrumb-item"><a href="#!">Info Program Masjid</a></li>
                        </ul>
                    </div>
                </div>
                {{-- END BREADCRUMD --}}
                <div class="page-body">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="card">
                                <div class="card-header">
                                    <h5>Info Program Masjid</h5>
                                    <div class="card-header-right">
                                        <a class="btn btn-primary" href="{{ URL('infoprogrammasjid/create') }}">
                                            <i class="icofont icofont-ui-add"></i>
                                            Add Program Masjid
                                        </a>
                                    </div>
                                </div>
                                <div class="card-block">

                                    <table id="example" class="display" style="width:100%">
                                        <thead>
                                            <tr>
                                                <th>No</th>
                                                <th>Tanggal</th>
                                                <th>Judul</th>
                                                <th>Konten</th>
                                                <th>Action</th>
                                            </tr>
                                        </thead>
                                        
                                        <tbody>
                                            @foreach ($m_info_program_masjids as $key => $data)
                                            <tr>
                                                <td>{{ ($key+1) }}</td>
                                                @if($data->tanggal != "")
                                                    <td>{{ date('d-m-Y', strtotime($data->tanggal)) }}</td>
                                                @else
                                                    <td>{{ $data->waktu_teks }}</td>
                                                @endif
                                                <td>{{ $data->judul }}</td>
                                                <td>{{ $data->konten }}</td>
                                                
                                                <td>
                                                    <a href="{{ route('infoprogrammasjid.edit', $data->id) }}" type="button" title="Edit" class="btn btn-warning btn-sm">
                                                        <i class="icofont icofont-pencil"></i>
                                                    </a>
                                                    
                                                    <form id="delete" action="{{ route('infoprogrammasjid.destroy', $data->id) }}" 
                                                        method="POST" style="display: inline;">
                                                        {{ csrf_field() }}
                                                        {{ method_field('DELETE') }}
                                                        <button title="Delete" class="btn btn-danger btn-sm"><i class="icofont icofont-trash"></i></button>
                                                    </form>
                                                </td>
                                            </tr>
                                            @endforeach
                                        </tbody>
                                    </table>

                                    

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- UNTUK SETTING COLOR -->
            <div id="styleSelector">
            </div>
        </div>
    </div>
</div>
                
@endsection

@section('js')
<script src="{{ asset('public/asset_admin/assets/js/datatables/js/datatables.min.js') }}"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $('#example').DataTable();
    } );
</script>

@endsection