routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () { return view('welcome');});
Route::get('/', 'FrontendController@index');
Route::get('masjid_v1/getWaktuAzan','FrontendController@getWaktuAzan');
Route::get('prokes', 'ProkesController@index');
Route::get('prokesSholatJumat', 'ProkesController@prokesJumat');
Route::get('masjid_v1/getWaktuIqomah','ProkesController@getWaktuIqomah');
Route::get('countdownblank', 'ProkesController@blankscreen');
Route::get('countdownblankSholatJumat', 'ProkesController@blankscreenJumat');

// * ROUTE BACK END
Route::get('/masjidadminlogin', function () {return view('backEND.loginmasjid');});

Route::group(['middleware' => 'auth'],function(){
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('users', 'UserController');
    Route::resource('infoprogrammasjid', 'InfoProgramMasjidController');
    Route::resource('infosholatjumat', 'InfoSholatJumatController');
    Route::resource('infokajianmingguan', 'InfoKajianMingguanController');
    Route::resource('infokepengurusan', 'InfoKepengurusanController');
    Route::resource('hadits', 'HaditsController');
    Route::resource('jedawaktu', 'JedaWaktuController');
   

    // * view create
    Route::get('actionviewbeforeazan', 'JedaWaktuController@createViewBeforeAzan');
    Route::get('actionviewiqomah', 'JedaWaktuController@createViewIqomah');

    // * action add
    Route::post("actioncreatebeforeazan", "JedaWaktuController@createActionBeforeAzan");
    Route::post("actioncreateiqomah", "JedaWaktuController@createActionIqomah");

    // * view edit
    Route::get('editviewbeforeazan/{id}', 'JedaWaktuController@vieweditBeforeAzan');
    Route::get('editviewiqomah/{id}', 'JedaWaktuController@vieweditIqomah');

    // * action update
    Route::get("actionupdatebeforeazan/{id}", "JedaWaktuController@updateActionBeforeAzan");
    Route::get("actionupdateiqomah/{id}", "JedaWaktuController@updateActionIqomah");

    // * action delete
    // Route::get("actiondeletebeforeazan/{id}", "JedaWaktuController@destroyBeforeAzan");
    // Route::get("actiondeleteiqomah/{id}", "JedaWaktuController@destroyIqomah");
  
    Route::get('UpdatePhotoEmpty/{id}', 'InfoSholatJumatController@UpdatePhotoEmpty')->name('UpdatePhotoEmpty.UpdatePhotoEmpty');
    Route::get('UpdatePhotoEmptyKajian/{id}', 'InfoKajianMingguanController@UpdatePhotoEmptyKajian')->name('UpdatePhotoEmptyKajian.UpdatePhotoEmptyKajian');
});

Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/InfoKajianMingguanController.php
<?php

namespace App\Http\Controllers;

use Hash;
use Auth;
use File;
use Storage;
use View;

use App\MInfoKajianMingguan;

use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Crypt;
use Illuminate\Support\Facades\DB;

class InfoKajianMingguanController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $data['m_info_kajian_mingguan'] = MInfoKajianMingguan::all();

        return view('backEND.InfoKajianMingguan.view', $data);
    }

    public function create()
    {
        return view('backEND.InfoKajianMingguan.create');
    }

    public function store(Request $request)
    {
        date_default_timezone_set('Asia/Jakarta');
        $currentuserid  = Auth::id();
        $today          = date("Y-m-d H:i:s"); 

        if($request->photo == "null" || $request->photo == ""){

            $user_photo_user     = 'user_profile.png';
            $path_photo_user     = 'storage/photo_info_kajian_mingguan/user_profile.png'; 

            $all_data_kajian = [
                'nama'          => $request->nama,
                'photo'         => $user_photo_user,
                'photo_path'    => $path_photo_user,
                'tanggal'       => date('Y-m-d', strtotime($request->tanggal)),
                'jam'           => $request->jam,
                'insert_by'     => $currentuserid,
                'created_at'    => $today,
            ];
        } else {

            $uploadedFile   = $request->file('file');        
            $path           = $request->file('photo')->store('public/photo_info_kajian_mingguan');
            $name_photo     = Str::substr(htmlspecialchars($path), 34, 87);
            $substrPath     = Str::substr($path, 6, 100);
            $pathDefault    = "storage".$substrPath;

            $all_data_kajian = [
                'nama'          => $request->nama,
                'photo'         => $name_photo,
                'photo_path'    => $pathDefault,
                'tanggal'       => date('Y-m-d', strtotime($request->tanggal)),
                'jam'           => $request->jam,
                'insert_by'     => $currentuserid,
                'created_at'    => $today,
            ];
        }

        //dd($all_data_kajian);die;
    
        $save = MInfoKajianMingguan::insert($all_data_kajian);
        if($save)
            return redirect('infokajianmingguan');
        else
            return redirect()->back()->withInput();
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $data['m_info_kajian_mingguan'] = MInfoKajianMingguan::find($id);
     
        return view('backEND.InfoKajianMingguan.edit')->with(['data' => $data]);
    }

    public function update(Request $request, $id)
    {
        date_default_timezone_set('Asia/Jakarta');
        $currentuserid  = Auth::id();
        $today          = date("Y-m-d H:i:s"); 
        $cekData        = MInfoKajianMingguan::where('id', $id)->first(); 
        //dd($request->photo);

        if($request->photo == "null" || $request->photo == ""){
            //dd('masuk 1');
            $user_photo_user     = 'user_profile.png';
            $path_photo_user     = 'storage/photo_info_kajian_mingguan/user_profile.png'; 

            $update_data_kajian = [
                'nama'          => $request->nama,
                'photo'         => $user_photo_user,
                'photo_path'    => $path_photo_user,
                'tanggal'       => date('Y-m-d', strtotime($request->tanggal)),
                'jam'           => $request->jam,
                'update_by'     => $currentuserid,
                'updated_at'    => $today,
            ];

        } else if($cekData['photo'] == $request->photo) {
            //dd('masuk 2');
            $update_data_kajian = [
                'nama'          => $request->nama,
                'tanggal'       => date('Y-m-d', strtotime($request->tanggal)),
                'jam'           => $request->jam,
                'update_by'     => $currentuserid,
                'updated_at'    => $today,
            ];
            
        } else {
            //dd('masuk 3');
            $uploadedFile   = $request->file('file');        
            $path           = $request->file('photo')->store('public/photo_info_kajian_mingguan');
            $name_photo     = Str::substr(htmlspecialchars($path), 34, 87);
            $substrPath     = Str::substr($path, 6, 100);
            $pathDefault    = "storage".$substrPath;

            $update_data_kajian = [
                'nama'          => $request->nama,
                'photo'         => $name_photo,
                'photo_path'    => $pathDefault,
                'tanggal'       => date('Y-m-d', strtotime($request->tanggal)),
                'jam'           => $request->jam,
                'update_by'     => $currentuserid,
                'updated_at'    => $today,
            ];
        }

        //dd($update_data_sholat); die;
        $updatedata = MInfoKajianMingguan::where('id',$id)->update($update_data_kajian);
        if($updatedata){
            $msg = 'Your data has been successfully updated!';
            return redirect('infokajianmingguan')->withSuccess($msg);
        } else {
            return redirect()->back()->withInput();
        }
    }

    public function destroy($id)
    {
        $infoKajian = MInfoKajianMingguan::find($id);
        $cekData    = MInfoKajianMingguan::where('id', $id)->first();
        
        //kondisi hapus file photo
        if($cekData['photo'] == 'user_profile.png'){
            if($infoKajian) {
                $infoKajian->destroy($id);
                $msg = 'Your data has been deleted!';
            } else {
                $msg = 'Please try again!';
            }
            return redirect()
                ->back()
                ->withSuccess($msg); 

        } else {
            $delete_Photo_dir   = $cekData['photo'];

            $filename = public_path().'/storage/photo_info_kajian_mingguan/'.$delete_Photo_dir;
            File::delete($filename);

            if($infoKajian) {
                $infoKajian->destroy($id);
                $msg = 'Your data has been deleted!';
            } else {
                $msg = 'Please try again!';
            }
            return redirect()
                ->back()
                ->withSuccess($msg); 
        }
    }

    public function UpdatePhotoEmptyKajian($id){
        //dd('masuk update Photo');die;
        $cekData          = MInfoKajianMingguan::where('id', $id)->first();
        if($cekData['photo'] == 'user_profile.png'){
            // dd('tidak bisa dihapus');
            // Set kosong pada field photo dan file path
            $emptyPhoto = [
                'photo' => "",
                'photo_path' => "",
            ];

            // update database user per id untuk field photo dan file path
            $updatePhoto = MInfoKajianMingguan::where('id',$id)->update($emptyPhoto);
            if($updatePhoto){
                return redirect()->back()->withInput();
            }
        } else {
            //dd('berhasil dihapus');
            $delete_Photo_dir   = $cekData['photo'];

            $filename = public_path().'/storage/photo_info_kajian_mingguan/'.$delete_Photo_dir;
            File::delete($filename);

            // Set kosong pada field photo dan file path
            $emptyPhoto = [
                'photo' => "",
                'photo_path' => "",
            ];

            // update database user per id untuk field photo dan file path
            $updatePhoto = MInfoKajianMingguan::where('id',$id)->update($emptyPhoto);
            if($updatePhoto){
                return redirect()->back()->withInput();
            }
        }
        
    }
}

resources/views/backEND/InfoKajianMingguan/create.blade.php
@extends('backEND.layouts.index')

@section('page-content')

<div class="pcoded-content">
        <div class="pcoded-inner-content">
           <div class="main-body">
              <div class="page-wrapper">
                 {{-- BREADCRUMD --}}
                 <div class="page-header">
                    <div class="page-header-title">
                       <h4>Create Info Kajian Mingguan</h4>
                    </div>
                    <div class="page-header-breadcrumb">
                       <ul class="breadcrumb-title">
                          <li class="breadcrumb-item">
                             <a href="index-2.html">
                             <i class="icofont icofont-home"></i>
                             </a>
                          </li>
                          <li class="breadcrumb-item"><a href="#!">Info Info Kajian Mingguan</a></li>
                          <li class="breadcrumb-item"><a href="#!">Create Info Kajian Mingguan</a></li>
                       </ul>
                    </div>
                 </div>
                 {{-- END BREADCRUMD --}}
                 <div class="page-body">
                    <div class="row">
                       <div class="col-lg-12">
                          <div class="card">
                             <div class="card-header">
                                <h5>Create Info Kajian Mingguan</h5>
                             </div>
                             <div class="card-block">
                                <form id="main" method="post" action="{{ URL('infokajianmingguan/') }}{{ isset($MInfoKajianMingguan) ? '/' . $MInfoKajianMingguan->id : '' }}" enctype="multipart/form-data" id="myReset">
                                {{ csrf_field() }}
                            	@if (isset($MInfoKajianMingguan))
									{{ method_field('PUT') }}
								@endif    
                                    <div class="form-group row">
                                        <label class="col-sm-2 col-form-label">Nama</label>
                                        <div class="col-sm-10">
                                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                            <input 
                                            type="text" 
                                            class="form-control form-control-danger" 
                                            name="nama" 
                                            required
                                            >
                                            <!-- @if (session()->has('name'))
                                            <span class="messages">*  {{ session('name') }}</span>
                                            @endif -->
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-sm-2 col-form-label">Upload Photo</label>
                                        <div class="col-sm-10">
                                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                            <input 
                                            type="file" 
                                            name="photo" 
                                            class="form-control"
                                            >
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-sm-2 col-form-label">Tanggal Acara Kajian</label>
                                        <div class="col-sm-5">
                                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                            <input 
                                            id="dropper-default" 
                                            class="form-control form-control-danger" 
                                            type="text" 
                                            name="tanggal" 
                                            required
                                            >
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-sm-2 col-form-label">Waktu Acara Kajian</label>
                                        <div class="col-sm-5">
                                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                            <input 
                                            id="dropper-default" 
                                            class="form-control form-control-danger" 
                                            type="time" 
                                            name="jam" 
                                            required
                                            >
                                        </div>
                                    </div>

                            
                                    <div class="form-group row">
                                        <label class="col-sm-2"></label>
                                        <div class="col-sm-10">
                                            <button type="submit" class="btn btn-danger m-b-0">Reset</button>
                                            <button type="submit" class="btn btn-primary m-b-0">Submit</button>
                                        </div>
                                    </div>
                                </form>
            
                             </div>
                          </div>
                       </div>
                    </div>
                 </div>
              </div>
              <!-- UNTUK SETTING COLOR -->
              <div id="styleSelector"></div>
           </div>
        </div>
     </div>

@endsection

@section('js')
<script src="{{ asset('public/vendor/unisharp/laravel-ckeditor/adapters/jquery.js') }}"></script>
<script type="text/javascript" src="{{ asset('public/asset_admin/bower_components/datedropper/datedropper.min.js') }}"></script>
<script>
   $('#dropper-default').dateDropper({
      theme: 'leaf'
   });
</script> 
@endsection

resources/views/backEND/InfoKajianMingguan/edit.blade.php
@extends('backEND.layouts.index')

@section('page-content')

<div class="pcoded-content">
        <div class="pcoded-inner-content">
           <div class="main-body">
              <div class="page-wrapper">
                 {{-- BREADCRUMD --}}
                 <div class="page-header">
                    <div class="page-header-title">
                       <h4>Update Info Kajian Mingguan</h4>
                    </div>
                    <div class="page-header-breadcrumb">
                       <ul class="breadcrumb-title">
                          <li class="breadcrumb-item">
                             <a href="index-2.html">
                             <i class="icofont icofont-home"></i>
                             </a>
                          </li>
                          <li class="breadcrumb-item"><a href="#!">Info Info Kajian Mingguan</a></li>
                          <li class="breadcrumb-item"><a href="#!">Update Info Kajian Mingguan</a></li>
                       </ul>
                    </div>
                 </div>
                 {{-- END BREADCRUMD --}}
                 <div class="page-body">
                    <div class="row">
                       <div class="col-lg-12">
                          <div class="card">
                             <div class="card-header">
                                <h5>Update Info Kajian Mingguan</h5>
                             </div>
                             <div class="card-block">
                                <form id="main" method="post" action="{{ URL::to('infokajianmingguan',$data['m_info_kajian_mingguan']->id)}}" enctype="multipart/form-data" id="myReset">
                                {{ csrf_field() }}
                                {{ method_field('put') }}  
                                    <div class="form-group row">
                                        <label class="col-sm-2 col-form-label">Nama</label>
                                        <div class="col-sm-10">
                                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                            <input 
                                            type="text" 
                                            class="form-control form-control-danger" 
                                            name="nama" 
                                            value="{{ isset($data['m_info_kajian_mingguan']) ? $data['m_info_kajian_mingguan']->nama : '' }}"
                                            required
                                            >
                                            <!-- @if (session()->has('name'))
                                            <span class="messages">*  {{ session('name') }}</span>
                                            @endif -->
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-sm-2 col-form-label">Photo</label>
                                        <div class="col-sm-5">
                                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                            @if($data['m_info_kajian_mingguan']->photo == "" || $data['m_info_kajian_mingguan']->photo == null)
                                                <input 
                                                    type="file" 
                                                    name="photo" 
                                                    class="form-control"
                                                >
                                            @else
                                                <div class="pull-right">
                                                    <a href="{{ URL('UpdatePhotoEmptyKajian/' . $data['m_info_kajian_mingguan']->id) }}" title="Delete Photo">
                                                        <img src="{{ URL::asset('public/asset_admin/image/close.png') }}" style="position: absolute;width: 35px;margin-top: 1px;margin-left: -115px;box-shadow: 0 0 25px -2px #b7b7b7;">
                                                    </a>
                                                </div>
                                                <input type="hidden" name="photo" value="{{ isset($data['m_info_kajian_mingguan']) ? $data['m_info_kajian_mingguan']->photo : '' }}" >
                                                <img src="{{ asset('public/'.$data['m_info_kajian_mingguan']->photo_path) }}" alt=""  style="border: 1px solid #fff;width: 300px;">
                                            @endif
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-sm-2 col-form-label">Tanggal Acara Kajian</label>
                                        <div class="col-sm-5">
                                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                            <input 
                                            id="dropper-default" 
                                            class="form-control form-control-danger" 
                                            type="text" 
                                            name="tanggal" 
                                            value="{{ isset($data['m_info_kajian_mingguan']) ? $data['m_info_kajian_mingguan']->tanggal : '' }}"
                                            required
                                            >
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-sm-2 col-form-label">Waktu Acara Kajian</label>
                                        <div class="col-sm-5">
                                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                            <input 
                                            id="dropper-default" 
                                            class="form-control form-control-danger" 
                                            type="time" 
                                            name="jam" 
                                            value="{{ isset($data['m_info_kajian_mingguan']) ? $data['m_info_kajian_mingguan']->jam : '' }}"
                                            required
                                            >
                                        </div>
                                    </div>

                            
                                    <div class="form-group row">
                                        <label class="col-sm-2"></label>
                                        <div class="col-sm-10">
                                            <button type="submit" class="btn btn-danger m-b-0">Reset</button>
                                            <button type="submit" class="btn btn-primary m-b-0">Update</button>
                                        </div>
                                    </div>
                                </form>
            
                             </div>
                          </div>
                       </div>
                    </div>
                 </div>
              </div>
              <!-- UNTUK SETTING COLOR -->
              <div id="styleSelector"></div>
           </div>
        </div>
     </div>

@endsection

@section('js')
<script src="{{ asset('public/vendor/unisharp/laravel-ckeditor/adapters/jquery.js') }}"></script>
<script type="text/javascript" src="{{ asset('public/asset_admin/bower_components/datedropper/datedropper.min.js') }}"></script>
<script>
   $('#dropper-default').dateDropper({
      theme: 'leaf'
   });
</script> 
@endsection

resources/views/backEND/InfoKajianMingguan/view.blade.php
@extends('backEND.layouts.index')

@section('page-content')
<div class="pcoded-content">
    <div class="pcoded-inner-content">
        <div class="main-body">
            <div class="page-wrapper">
                {{-- BREADCRUMD --}}
                <div class="page-header">
                    <div class="page-header-title">
                        <h4>Info Kajian Mingguan</h4>
                    </div>
                    <div class="page-header-breadcrumb">
                        <ul class="breadcrumb-title">
                            <li class="breadcrumb-item">
                                <a href="index-2.html">
                                <i class="icofont icofont-home"></i>
                                </a>
                            </li>
                            {{-- <li class="breadcrumb-item"><a href="#!"></a></li> --}}
                            <li class="breadcrumb-item"><a href="#!">Info Kajian Mingguan</a></li>
                        </ul>
                    </div>
                </div>
                {{-- END BREADCRUMD --}}
                <div class="page-body">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="card">
                                <div class="card-header">
                                    <h5>Info Kajian Mingguan</h5>
                                    <div class="card-header-right">
                                        <a class="btn btn-primary" href="{{ URL('infokajianmingguan/create') }}">
                                            <i class="icofont icofont-ui-add"></i>
                                            Add Info Kajian Mingguan
                                        </a>
                                    </div>
                                </div>
                                <div class="card-block">

                                    <table id="example" class="display" style="width:100%">
                                        <thead>
                                            <tr>
                                                <th>No</th>
                                                <th>Nama</th>
                                                <th>Photo</th>
                                                <th>Tanggal</th>
                                                <th>Jam</th>
                                                <th>Action</th>
                                            </tr>
                                        </thead>
                                        
                                        <tbody>
                                            @foreach ($m_info_kajian_mingguan as $key => $data)
                                            <tr>
                                                <td>{{ ($key+1) }}</td>
                                                <td>{{ $data->nama }}</td>
                                                <td>
                                                    <img src="{{ asset('public/storage/photo_info_kajian_mingguan/'.$data->photo) }}" class="img img-thumbnail" style="width: 100px;">
                                                </td>
                                                <td>{{ date('d-m-Y', strtotime($data->tanggal)) }}</td>
                                                <td>{{ $data->jam }}</td>
                                                <td>
                                                    <a href="{{ route('infokajianmingguan.edit', $data->id) }}" type="button" title="Edit" class="btn btn-warning btn-sm">
                                                        <i class="icofont icofont-pencil"></i>
                                                    </a>
                                                    
                                                    <form id="delete" action="{{ route('infokajianmingguan.destroy', $data->id) }}" 
                                                        method="POST" style="display: inline;">
                                                        {{ csrf_field() }}
                                                        {{ method_field('DELETE') }}
                                                        <button title="Delete" class="btn btn-danger btn-sm"><i class="icofont icofont-trash"></i></button>
                                                    </form>
                                                </td>
                                            </tr>
                                            @endforeach
                                        </tbody>
                                    </table>

                                    

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- UNTUK SETTING COLOR -->
            <div id="styleSelector">
            </div>
        </div>
    </div>
</div>
                
@endsection

@section('js')
<script src="{{ asset('public/asset_admin/assets/js/datatables/js/datatables.min.js') }}"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $('#example').DataTable();
    } );
</script>

@endsection