routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () { return view('welcome');});
Route::get('/', 'FrontendController@index');
Route::get('masjid_v1/getWaktuAzan','FrontendController@getWaktuAzan');
Route::get('prokes', 'ProkesController@index');
Route::get('prokesSholatJumat', 'ProkesController@prokesJumat');
Route::get('masjid_v1/getWaktuIqomah','ProkesController@getWaktuIqomah');
Route::get('countdownblank', 'ProkesController@blankscreen');
Route::get('countdownblankSholatJumat', 'ProkesController@blankscreenJumat');

// * ROUTE BACK END
Route::get('/masjidadminlogin', function () {return view('backEND.loginmasjid');});

Route::group(['middleware' => 'auth'],function(){
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('users', 'UserController');
    Route::resource('infoprogrammasjid', 'InfoProgramMasjidController');
    Route::resource('infosholatjumat', 'InfoSholatJumatController');
    Route::resource('infokajianmingguan', 'InfoKajianMingguanController');
    Route::resource('infokepengurusan', 'InfoKepengurusanController');
    Route::resource('hadits', 'HaditsController');
    Route::resource('jedawaktu', 'JedaWaktuController');
   

    // * view create
    Route::get('actionviewbeforeazan', 'JedaWaktuController@createViewBeforeAzan');
    Route::get('actionviewiqomah', 'JedaWaktuController@createViewIqomah');

    // * action add
    Route::post("actioncreatebeforeazan", "JedaWaktuController@createActionBeforeAzan");
    Route::post("actioncreateiqomah", "JedaWaktuController@createActionIqomah");

    // * view edit
    Route::get('editviewbeforeazan/{id}', 'JedaWaktuController@vieweditBeforeAzan');
    Route::get('editviewiqomah/{id}', 'JedaWaktuController@vieweditIqomah');

    // * action update
    Route::get("actionupdatebeforeazan/{id}", "JedaWaktuController@updateActionBeforeAzan");
    Route::get("actionupdateiqomah/{id}", "JedaWaktuController@updateActionIqomah");

    // * action delete
    // Route::get("actiondeletebeforeazan/{id}", "JedaWaktuController@destroyBeforeAzan");
    // Route::get("actiondeleteiqomah/{id}", "JedaWaktuController@destroyIqomah");
  
    Route::get('UpdatePhotoEmpty/{id}', 'InfoSholatJumatController@UpdatePhotoEmpty')->name('UpdatePhotoEmpty.UpdatePhotoEmpty');
    Route::get('UpdatePhotoEmptyKajian/{id}', 'InfoKajianMingguanController@UpdatePhotoEmptyKajian')->name('UpdatePhotoEmptyKajian.UpdatePhotoEmptyKajian');
});

Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/InfoKepengurusanController.php
<?php

namespace App\Http\Controllers;

use Hash;
use Auth;
use Storage;
use View;

use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Crypt;
use Illuminate\Support\Facades\DB;

class InfoKepengurusanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/backEND/InfoKepengurusan/view.blade.php
@extends('backEND.layouts.index')

@section('page-content')
<div class="pcoded-content">
    <div class="pcoded-inner-content">
        <div class="main-body">
            <div class="page-wrapper">
                {{-- BREADCRUMD --}}
                <div class="page-header">
                    <div class="page-header-title">
                        <h4>Info Sholat Jum'at</h4>
                    </div>
                    <div class="page-header-breadcrumb">
                        <ul class="breadcrumb-title">
                            <li class="breadcrumb-item">
                                <a href="index-2.html">
                                <i class="icofont icofont-home"></i>
                                </a>
                            </li>
                            {{-- <li class="breadcrumb-item"><a href="#!"></a></li> --}}
                            <li class="breadcrumb-item"><a href="#!">Info Sholat Jum'at</a></li>
                        </ul>
                    </div>
                </div>
                {{-- END BREADCRUMD --}}
                <div class="page-body">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="card">
                                <div class="card-header">
                                    <h5>Info Sholat Jum'at</h5>
                                    <div class="card-header-right">
                                        <a class="btn btn-primary" href="{{ URL('users/create') }}">
                                            <i class="icofont icofont-ui-add"></i>
                                            Add Info Sholat Jum'at
                                        </a>
                                    </div>
                                </div>
                                <div class="card-block">

                                    <table id="example" class="display" style="width:100%">
                                        <thead>
                                            <tr>
                                                <th>No</th>
                                                <th>Nama</th>
                                                <th>Photo</th>
                                                <th>Sebagai</th>
                                                <th>Action</th>
                                            </tr>
                                        </thead>
                                        
                                        <tbody>
                                            @foreach ($m_info_sholat_jumat as $key => $data)
                                            <tr>
                                                <td>{{ ($key+1) }}</td>
                                                <td>{{ $data->nama }}</td>
                                                <td>{{ $data->photo }}</td>
                                                <td>{{ $data->sebagai }}</td>
                                                
                                                <td>
                                                    <a href="{{ route('infosholatjumat.edit', $data->id) }}" type="button" title="Edit" class="btn btn-warning btn-sm">
                                                        <i class="icofont icofont-pencil"></i>
                                                    </a>
                                                    
                                                    <a href="{{ route('infosholatjumat.destroy', $data->id) }}" type="button" title="Delete" class="btn btn-danger btn-sm" 
                                                            onclick="event.preventDefault(); document.getElementById('delete').submit();">
                                                        <i class="icofont icofont-trash"></i>
                                                    </a>
                                                    <form id="delete" action="{{ route('infosholatjumat.destroy', $data->id) }}" 
                                                        method="POST" style="display: none;">
                                                        {{ csrf_field() }}
                                                        {{ method_field('DELETE') }}
                                                    </form>
                                                </td>
                                            </tr>
                                            @endforeach
                                        </tbody>
                                    </table>

                                    

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- UNTUK SETTING COLOR -->
            <div id="styleSelector">
            </div>
        </div>
    </div>
</div>
                
@endsection

@section('js')
<script src="{{ asset('public/asset_admin/assets/js/datatables/js/datatables.min.js') }}"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $('#example').DataTable();
    } );
</script>

@endsection